### ISSUE TITLE
Very small security issue

### ISSUE THREAD

**Issue by GitKepler** [MrScriptX/Discord_Bot#1]
https://github.com/MrScriptX/Discord_Bot/blob/7db459e4617a47f7c148754a871e7cb18eb7b082/Discord_Bot/Program.cs#L37
https://github.com/MrScriptX/Discord_Bot/blob/b54cf7571d47be039c88530638e96ca85e66dc2a/Discord_Bot/Program.cs#L33

**Comment by MrScriptX** [comment]
both token and database info are invalid
